# Generated by Django 6.0.2 on 2026-03-03 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_otpverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPVerification',
        ),
    ]
